spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:file:./database/h2
    username: Paul123
    password: password123
  jpa:
    open-in-view: false
    show-sql: true
    hibernate.ddl-auto: update